name: build
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/**
    - build_script/**
jobs:
  build_linux_vcpkg_x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_linux_vcpkg_x64.sh
    - name: Package
      run: 7z a libclamav_linux_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_linux_vcpkg_x64
        path: output/*

  build_linux_vcpkg_arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_linux_vcpkg_arm64.sh
    - name: Package
      run: 7z a libclamav_linux_vcpkg_arm64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_linux_vcpkg_arm64
        path: output/*

  build_osx_vcpkg_x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_osx_vcpkg_x64.sh
    - name: Package
      run: 7z a libclamav_osx_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_osx_vcpkg_x64
        path: output/*

  build_osx_vcpkg_arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_osx_vcpkg_arm64.sh
    - name: Package
      run: 7z a libclamav_osx_vcpkg_arm64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_osx_vcpkg_arm64
        path: output/*

  build_win_vcpkg_x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: .\build_script\libclamav_win_vcpkg_x64.ps1
    - name: Package
      run: 7z a libclamav_win_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_win_vcpkg_x64
        path: output/*
  
  build_win_vcpkg_arm64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: .\build_script\libclamav_win_vcpkg_arm64.ps1
    - name: Package
      run: 7z a libclamav_win_vcpkg_arm64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_win_vcpkg_arm64
        path: output/*
