name: build
on:
  push:
    branches:
    - main
jobs:
  build_win64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: ./libclamav_osx_vcpkg_x64.sh
    - name: Package
      run: 7z a libclamav_osx_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_osx_vcpkg_x64
        path: libclamav_osx_vcpkg_x64.zip

