name: release
on: 
  push:
    tags:
    - v*
jobs:
  build_linux_vcpkg_x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_linux_vcpkg_x64.sh
    - name: Package
      run: 7z a libclamav_linux_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_linux_vcpkg_x64
        path: libclamav_linux_vcpkg_x64.zip

  build_linux_vcpkg_arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_linux_vcpkg_arm64.sh
    - name: Package
      run: 7z a libclamav_linux_vcpkg_arm64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_linux_vcpkg_arm64
        path: output/*

  build_osx_vcpkg_x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_osx_vcpkg_x64.sh
    - name: Package
      run: 7z a libclamav_osx_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_osx_vcpkg_x64
        path: libclamav_osx_vcpkg_x64.zip
  
  build_osx_vcpkg_arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: bash build_script/libclamav_osx_vcpkg_arm64.sh
    - name: Package
      run: 7z a libclamav_osx_vcpkg_arm64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_osx_vcpkg_arm64
        path: output/*

  build_win_vcpkg_x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: .\build_script\libclamav_win_vcpkg_x64.ps1
    - name: Package
      run: 7z a libclamav_win_vcpkg_x64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_win_vcpkg_x64
        path: libclamav_win_vcpkg_x64.zip

  build_win_vcpkg_arm64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build lib
      run: .\build_script\libclamav_win_vcpkg_arm64.ps1
    - name: Package
      run: 7z a libclamav_win_vcpkg_arm64.zip ./output/*
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: libclamav_win_vcpkg_arm64
        path: output/*

  release_all:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        draft: false
        prerelease: false
        release_name: Release ${{github.ref}}
        tag_name: ${{github.ref}}
    - uses: actions/download-artifact@v3
      with:
        path: ./
    - name: Prepare artifact
      run: mv -f */*.zip ./ || true
      
    - name: Upload build_linux_vcpkg_x64
      id: upload-release-asset-build_linux_vcpkg_x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_content_type: application/zip
        asset_name: libclamav_linux_vcpkg_x64.zip
        asset_path: libclamav_linux_vcpkg_x64.zip
        upload_url: ${{steps.create_release.outputs.upload_url}}

    - name: Upload build_linux_vcpkg_arm64
      id: upload-release-asset-build_linux_vcpkg_arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_content_type: application/zip
        asset_name: libclamav_linux_vcpkg_arm64.zip
        asset_path: libclamav_linux_vcpkg_arm64.zip
        upload_url: ${{steps.create_release.outputs.upload_url}}

    - name: Upload build_osx_vcpkg_x64
      id: upload-release-asset-build_osx_vcpkg_x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_content_type: application/zip
        asset_name: libclamav_osx_vcpkg_x64.zip
        asset_path: libclamav_osx_vcpkg_x64.zip
        upload_url: ${{steps.create_release.outputs.upload_url}}
        
    - name: Upload build_win_vcpkg_arm64
      id: upload-release-asset-build_win_vcpkg_arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_content_type: application/zip
        asset_name: libclamav_win_vcpkg_arm64.zip
        asset_path: libclamav_win_vcpkg_arm64.zip
        upload_url: ${{steps.create_release.outputs.upload_url}}

    needs:
    - build_linux_vcpkg_x64
    - build_linux_vcpkg_arm64
    - build_osx_vcpkg_x64
    - build_osx_vcpkg_arm64
    - build_win_vcpkg_x64
    - build_win_vcpkg_arm64